### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ciricc** [navneetsharmaui/discover-twitter-spaces#2]
Getting `request.query replaced by request.url.searchParams` error.
And `$page.path has been replaced by $page.url.pathname` on the latest sveltekit version.

**Comment by navneetsharmaui** [comment]
@ciricc thanks for raising the issue. I've changed the sveltekit version from `next` to latest exact version number. It will not cause issues from now own as everyone will use the same sveltekit version instead of next.
